export default [
    {
        img: "https://i.ibb.co/Q8MJc4v/63125f63-5cd8-4667-bc65-ba55b9823f1d.jpg",
        title: "smash   burguer (bacon-cheddaar)",
        popularity: 5,
        rating: 5,
        deliveryTime: "15-25 min",
        deliveryPrice: 1.99,
        Dietary: "",
    },
    {
        img: "https://s2.glbimg.com/9zc9T-9LwXwKG_8XOq_9EF67bSQ=/620x455/e.glbimg.com/og/ed/f/original/2021/04/30/receita-hamburguer-smash-burguer-bacon-cheddaar.jpg",
        title: "smash   burguer (bacon-cheddaar)",
        popularity: 5,
        rating: 4,
        deliveryTime: "10-20 min",
        deliveryPrice: 1.25,
        Dietary: "",
    },
    {
        img: "https://s2.glbimg.com/9zc9T-9LwXwKG_8XOq_9EF67bSQ=/620x455/e.glbimg.com/og/ed/f/original/2021/04/30/receita-hamburguer-smash-burguer-bacon-cheddaar.jpg",
        title: "smash   burguer (bacon-cheddaar)",
        popularity: 5,
        rating: 4,
        deliveryTime: "20-30 min",
        deliveryPrice: 2.25,
        Dietary: "",
    },
    {
        img: "https://s2.glbimg.com/9zc9T-9LwXwKG_8XOq_9EF67bSQ=/620x455/e.glbimg.com/og/ed/f/original/2021/04/30/receita-hamburguer-smash-burguer-bacon-cheddaar.jpg",
        title: "smash   burguer (bacon-cheddaar)",
        popularity: 5,
        rating: 3,
        deliveryTime: "10-25 min",
        deliveryPrice: 0.75,
        Dietary: "",
    },
    {
        img: "https://s2.glbimg.com/9zc9T-9LwXwKG_8XOq_9EF67bSQ=/620x455/e.glbimg.com/og/ed/f/original/2021/04/30/receita-hamburguer-smash-burguer-bacon-cheddaar.jpg",
        title: "smash   burguer (bacon-cheddaar)",
        popularity: 5,
        rating: 2,
        deliveryTime: "15-25 min",
        deliveryPrice: 2,
        Dietary: "",
    },
    {
        img: "https://s2.glbimg.com/9zc9T-9LwXwKG_8XOq_9EF67bSQ=/620x455/e.glbimg.com/og/ed/f/original/2021/04/30/receita-hamburguer-smash-burguer-bacon-cheddaar.jpg",
        title: "smash   burguer (bacon-cheddaar)",
        popularity: 5,
        rating: 5,
        deliveryTime: "15-25 min",
        deliveryPrice: 2,
        Dietary: "",
    },
    {
        img: "https://s2.glbimg.com/9zc9T-9LwXwKG_8XOq_9EF67bSQ=/620x455/e.glbimg.com/og/ed/f/original/2021/04/30/receita-hamburguer-smash-burguer-bacon-cheddaar.jpg",
        title: "smash   burguer (bacon-cheddaar)",
        popularity: 5,
        rating: 5,
        deliveryTime: "15-25 min",
        deliveryPrice: 2,
        Dietary: "",
    },
    {
        img: "https://s2.glbimg.com/9zc9T-9LwXwKG_8XOq_9EF67bSQ=/620x455/e.glbimg.com/og/ed/f/original/2021/04/30/receita-hamburguer-smash-burguer-bacon-cheddaar.jpg",
        title: "smash   burguer (bacon-cheddaar)",
        popularity: 5,
        rating: 5,
        deliveryTime: "15-25 min",
        deliveryPrice: 2,
        Dietary: "",
    },
    {
        img: "https://s2.glbimg.com/9zc9T-9LwXwKG_8XOq_9EF67bSQ=/620x455/e.glbimg.com/og/ed/f/original/2021/04/30/receita-hamburguer-smash-burguer-bacon-cheddaar.jpg",
        title: "smash   burguer (bacon-cheddaar)",
        popularity: 5,
        rating: 5,
        deliveryTime: "15-25 min",
        deliveryPrice: 2,
        Dietary: "",
    },
    {
        img: "https://s2.glbimg.com/9zc9T-9LwXwKG_8XOq_9EF67bSQ=/620x455/e.glbimg.com/og/ed/f/original/2021/04/30/receita-hamburguer-smash-burguer-bacon-cheddaar.jpg",
        title: "smash   burguer (bacon-cheddaar)",
        popularity: 5,
        rating: 5,
        deliveryTime: "15-25 min",
        deliveryPrice: 2,
        Dietary: "",
    },
    {
        img: "https://s2.glbimg.com/9zc9T-9LwXwKG_8XOq_9EF67bSQ=/620x455/e.glbimg.com/og/ed/f/original/2021/04/30/receita-hamburguer-smash-burguer-bacon-cheddaar.jpg",
        title: "smash   burguer (bacon-cheddaar)",
        popularity: 5,
        rating: 5,
        deliveryTime: "15-25 min",
        deliveryPrice: 2,
        Dietary: "",
    },
    {
        img: "https://s2.glbimg.com/9zc9T-9LwXwKG_8XOq_9EF67bSQ=/620x455/e.glbimg.com/og/ed/f/original/2021/04/30/receita-hamburguer-smash-burguer-bacon-cheddaar.jpg",
        title: "smash   burguer (bacon-cheddaar)",
        popularity: 5,
        rating: 5,
        deliveryTime: "15-25 min",
        deliveryPrice: 2,
        Dietary: "",
    },
    {
        img: "https://s2.glbimg.com/9zc9T-9LwXwKG_8XOq_9EF67bSQ=/620x455/e.glbimg.com/og/ed/f/original/2021/04/30/receita-hamburguer-smash-burguer-bacon-cheddaar.jpg",
        title: "smash   burguer (bacon-cheddaar)",
        popularity: 5,
        rating: 5,
        deliveryTime: "15-25 min",
        deliveryPrice: 2,
        Dietary: "",
    },
    {
        img: "https://s2.glbimg.com/9zc9T-9LwXwKG_8XOq_9EF67bSQ=/620x455/e.glbimg.com/og/ed/f/original/2021/04/30/receita-hamburguer-smash-burguer-bacon-cheddaar.jpg",
        title: "smash   burguer (bacon-cheddaar)",
        popularity: 5,
        rating: 5,
        deliveryTime: "15-25 min",
        deliveryPrice: 2,
        Dietary: "",
    },
    {
        img: "https://s2.glbimg.com/9zc9T-9LwXwKG_8XOq_9EF67bSQ=/620x455/e.glbimg.com/og/ed/f/original/2021/04/30/receita-hamburguer-smash-burguer-bacon-cheddaar.jpg",
        title: "smash   burguer (bacon-cheddaar)",
        popularity: 5,
        rating: 5,
        deliveryTime: "15-25 min",
        deliveryPrice: 2,
        Dietary: "",
    },
]